# Generated by Django 5.1.4 on 2024-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignresult',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
